name: Kernel Compiler
on:
  watch:
    types: [started]

  workflow_dispatch:

jobs:
  build:
    name: Compile NeñaOnly2025 + NoKernelSU
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4

    - name: Setup build kernel environment
      run: |
        sudo apt update
        sudo apt install libc6-dev clang flex bison libssl-dev bc python3 zip unzip git lld llvm zstd tar wget
        mkdir -p $GITHUB_WORKSPACE/kernel_workspace
        
    - name: Download NeutronClang
      run: |
        cd $GITHUB_WORKSPACE/kernel_workspace
        mkdir clang
        cd clang
        bash <(curl -s "https://raw.githubusercontent.com/Neutron-Toolchains/antman/main/antman") -S
        pwd
        export PATH="$GITHUB_WORKSPACE/kernel_workspace/clang/bin:$PATH"
        
    - name: Download kernel source 
      run: |
        cd $GITHUB_WORKSPACE/kernel_workspace
        git clone https://github.com/kirilll1aliuk/zelo-sweet kernel --depth=1
        
    - name: Compiling Kernel
      run: |
        cd $GITHUB_WORKSPACE/kernel_workspace/kernel
        chmod +x sweet.sh
        ./sweet.sh
        filename=$(find . -name Quick* -printf '%f\n')
        echo $filename
        echo "FILENAME=$filename" >> $GITHUB_ENV
        
    - name: Uploading Kernel
      uses: actions/upload-artifact@v4
      with:
        name: NeñaOnly
        path: ${{ github.workspace }}/kernel_workspace/kernel/${{ env.FILENAME }}
